version: "3.3"

services:
  crm_connector_api:
    build: .
    environment:
      - DB_URL=jdbc:postgresql://localhost:5433/postgres
      - DB_USERNAME=crm
      - DB_PASSWORD=1329
    container_name: crm_connector_api
    ports:
      - "3131:3131"
    depends_on:
      - crm_connector_db
    networks:
      - crm_net

  crm_connector_db:
    image: postgres
    container_name: crm_connector_db
    restart: always
    ports:
      - "5433:5432"  
    environment:
      POSTGRES_DB: crm-connector
      POSTGRES_USER: crm
      POSTGRES_PASSWORD: 1329
    networks:
      - crm_net

networks:
  crm_net:
    driver: bridge
